apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-06-03T15:29:44Z"
  generateName: www-d659894f-
  labels:
    pod-template-hash: d659894f
    run: www
  name: www-d659894f-v745x
  namespace: carlostaffe
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: www-d659894f
    uid: 698a7aab-8614-11e9-8e25-fa163e921399
  resourceVersion: "34160344"
  selfLink: /api/v1/namespaces/carlostaffe/pods/www-d659894f-v745x
  uid: 69951d23-8614-11e9-8e25-fa163e921399
spec:
  containers:
  - image: bitnami/nginx
    imagePullPolicy: Always
    name: www
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-975bd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kube-um-k8s-node-nf-5
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-975bd
    secret:
      defaultMode: 420
      secretName: default-token-975bd
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-06-03T15:29:44Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-06-03T15:30:16Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-06-03T15:30:16Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-06-03T15:29:44Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://0d6e8bc10015387011df414122fcafa1aacdb35e6cd9498089c1631ea167ae96
    image: bitnami/nginx:latest
    imageID: docker-pullable://bitnami/nginx@sha256:3b870ef13043b3c5bdd64267721add231f39dd96fdac82531dcbe06d67ca4911
    lastState: {}
    name: www
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-06-03T15:30:15Z"
  hostIP: 192.168.186.16
  phase: Running
  podIP: 10.233.70.206
  qosClass: BestEffort
  startTime: "2019-06-03T15:29:44Z"
