apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: www
  name: www
spec:
  replicas: 3
  selector:
    matchLabels:
      run: www
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: www
    spec:
      containers:
      - image: bitnami/nginx:1.14.0
        name: www
        resources: {}
status: {}
