apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-prod
  labels:
    run: db-sts
spec:
  selector:
    matchLabels:
      run: db-sts
  serviceName: "db-sts"
  template:
    metadata:
      generateName: db-prod
      labels:
        run: db-sts
    spec:
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.25.0"
        imagePullPolicy: "IfNotPresent"
        command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql 
      containers:
        - name: db-prod
          image: mysql:5.7
          imagePullPolicy: Always
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret-sts
                  key: db-name
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret-sts
                  key: db-password
          ports:
            - name: db-sts
              containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql-data
            - mountPath: "/docker-entrypoint-initdb.d/"
              name: db-schema-data
      volumes:
        - name: secret-volume
          secret:
            secretName: db-secret-sts

        - configMap: 
            name: db-schema-data
          name: db-schema-data
  volumeClaimTemplates:
   - metadata:
       name: mysql-data
     spec:
       accessModes: [ "ReadWriteOnce" ]
       #storageClassName: "openebs-standalone"
       resources:
         requests:
           storage: 1Gi
