apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: web-test
  name: web-test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: web-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: web-test
    spec:
      containers:
      - image: bitnami/nginx:1.14.0
        name: web-test
        volumeMounts:
          - mountPath: "/temp"
            name: config-data
        resources: {}
      volumes:
        - configMap:
            name: prueba
          name: config-data
status: {}
