apiVersion: v1
data:
  oauth2_proxy_client_id: OTk5MDFiNTE2MzkyYTllOTc4ODg=
  oauth2_proxy_client_secret: ZTM1OTY0YzQ1N2ZlM2VhYWU2NDRkYTE4YTIwODZhMzAyODQ0ZjM0NA==
  oauth2_proxy_cookie_secret: cjRQU3pSemdoblVTN3E1TjBoV2VsUT09
kind: Secret
metadata:
  creationTimestamp: null
  name: oauth2-proxy-secrets
